### PR TITLE
Update for Relay v1.x API changes

### LINKED ISSUE #33: react-relay/classic usage?
Hey @edvinerikson, first, thanks for putting this together in the first place. We've been using it extensively for the last 6 months.

I was wondering if you have any thoughts on how to use this alongside relay 1.0. I'd love to be able to use it with relay/classic so that we can incrementally upgrade to relay-modern (using the relay-modern subscriptions requires moving to the relay-modern store, which requires upgrading everything at once).

I tried forking this bad-boy, upgrading to react-relay 1.0 and importing `react-relay/classic` instead of `react-relay`, but I can't seem to get it to work. I assume (although I don't _know_) that it's because the direct imports you have from `react-relay/lib...` now point to the relay-modern versions, but was curious if you had thoughts.

Thanks!

### PR DESCRIPTION
**Pull request by taion**
Closes #33

### CODE REVIEW

**Comment by taion** [comment]
@voxmatt

That error message about abstract class is just because Yarn and npm@5 install file dependencies as links. Otherwise the API changes were totally straightforward.

Not sure what the right way to set up the dependency in the demo project is, though. I think "set it to the next version" is the best I can do here. `^1.0.1` from npm would be wrong, `file:../..` doesn't work any more, and setting up a `postinstall` script to manually pack and install would be annoying. Maybe https://www.npmjs.com/package/install-local.

**Comment by edvinerikson** [comment]
Awesome, Thanks! 🎉

**Comment by voxmatt** [comment]
Okay, it looks like this may be slightly trickier than originally thought. I may not be interpreting this correctly, but it looks as thought Relay 1.0 brought a subscribe method to the classic Environment:
https://github.com/facebook/relay/blob/master/packages/react-relay/classic/store/RelayEnvironment.js

The `subscribe` method for the classic environment is called in the process of fragment resolution when using the `react-relay/compat` `createFragmentContainer` method, even when no subscriptions are present. This, as you may expect, collides with the `subscribe` method provided by the relay-subscriptions environment and fails.

I _think_ it may be as simple as changing the name of the `subscribe` method provided by relay-subscriptions environment?

I'm going to give it a shot and maybe I'll have a fork for you.

**Comment by voxmatt** [comment]
I think renaming works: https://github.com/edvinerikson/relay-subscriptions/pull/37

**Comment by taion** [comment]
Interesting. That's a very different `subscribe` too, right? I'd call it `sendSubscription`.

**Pull request merged**
